[package]
name = "ipc-rs"
version = "0.4.2"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]

[dependencies]
nix = "0.11.0"
libc = "0.2.43"
serde = { version = "1.0.71", features = ["derive"] }
serde_json = "1.0"
